### ISSUE TITLE
Error with VCFcorr_alleles.py script

### ISSUE THREAD

**Issue by jessicarick** [Gabaldonlab/haplotypo#3]
Thanks for building such a useful pipeline! I'm happy to have found it, because it looks like it should work for exactly what I need.

I've been working on getting the pipeline working for me, but unfortunately have run into an error in the `VCFcorr_alleles.py` script that I believe is related to it having a hard time parsing my VCF files, but I haven't been able to figure out how to fix it myself. The error that I'm getting is:

```
Traceback (most recent call last):
  File "haplotypo/bin/3.5/VCFcorr_alleles.py.", line 391, in <module>
    myList.append([val['chr'][0], val['position'][0],'.',val['reference'][0], val['alternative'][0],'.','.','.','GT:AD:DP\t%s:%s,%s:%s' % (val['GT'][0], val['AD'][0][0],val['AD'][0][1], val['DP'][0])])
TypeError: 'NoneType' object is not subscriptable
```
I've used the GATK pipeline in the `var_calling.py` script for variant calling (except using VCFtools for the last step to retain only PASS SNPs), and my VCF variant lines look like this:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  hapA
chr88_hapA      42      .       T       C       523.64  PASS    .       GT:AD:DP:FT:GQ:PL       0/1:35,22:57:heterozygous:99:531,0,1333
chr88_hapA      64      .       C       T       689.64  PASS    .       GT:AD:DP:FT:GQ:PL       0/1:42,25:67:heterozygous:99:697,0,1331
chr88_hapA      86      .       T       G       569.64  PASS    .       GT:AD:DP:FT:GQ:PL       0/1:40,22:62:heterozygous:99:577,0,1337
```
I'm also attaching a small test VCF with only the first 25000 lines for both hapA and hapB, in case those are useful for reproducing the problem (these came from the hapA.pass.snp.vcf and hapB.pass.snp.vcf files). I'm using python 3.6.3.

Thank you!

**Edit**: after a little more playing around, it appears that this error is connected with using the `-amb 1` option. I was able to successfully run the script using `-amb 0` and `-amb 2`.

[hapB.small.vcf.gz](https://github.com/Gabaldonlab/haplotypo/files/7183856/hapB.small.vcf.gz)
[hapA.small.vcf.gz](https://github.com/Gabaldonlab/haplotypo/files/7183857/hapA.small.vcf.gz)

**Comment by cintapq** [comment]
Hi Jessi,

Thanks for using Haplotypo, it's nice hearing that this is a usefulful tool ;)

You are totally right, your issue it's related with the ambiguity option. I've check your vcf and it contains alternative alleles that contain an *, this definetely will make the script to fail. I suggest you to use -amb 0 or -amb 2. Alternatively, you could remove the positions containing the * and run it again with -amb 1. 

Sorry for the inconvenineces, I hope this helps.

Best,
Cinta
